// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskSharpHTTP.Models;

namespace Parcial.Migrations
{
    [DbContext(typeof(DbCandidatosContext))]
    [Migration("20190725055149_vvv")]
    partial class vvv
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskSharpHTTP.Models.Candidatos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCa");

                    b.Property<int>("Votos");

                    b.HasKey("Id");

                    b.ToTable("CandidatosList");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.Votantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<int?>("CandidatosId");

                    b.Property<int>("IdCandidatos");

                    b.Property<string>("Nombre");

                    b.Property<string>("NumeroDeId");

                    b.HasKey("Id");

                    b.HasIndex("CandidatosId");

                    b.ToTable("VotantesList");
                });

            modelBuilder.Entity("TaskSharpHTTP.Models.Votantes", b =>
                {
                    b.HasOne("TaskSharpHTTP.Models.Candidatos", "Candidatos")
                        .WithMany()
                        .HasForeignKey("CandidatosId");
                });
#pragma warning restore 612, 618
        }
    }
}
